In [1]:
import numpy as np
import matplotlib.pyplot as plt
import sys
sys.path.append('/Users/sebastian/Documents/KTH/Year 1/DD2437 Artificial Neural Networks and Deep Architectures/lab_repo/DD2437_ANNs/lab2')
from rdf import *
from helper import *

In [2]:
# Training data
x_train = np.arange(0,2*np.pi,0.1)
y_sin_train = np.sin(2*x_train)
y_square_train = np.sign(y_sin_train) # # 1 if sin(2x) >= 0, else -1

# Testing data
x_test = np.arange(0.5,2*np.pi,0.1)
y_sin_test = np.sin(2*x_test)
y_square_test = np.sign(y_sin_test) # # 1 if sin(2x) >= 0, else -1

print(f"Training samples: {len(x_train)}")
print(f"Testing samples: {len(x_test)}")

Training samples: 63
Testing samples: 58


In [3]:
num_centers = 4
centers = np.linspace(0, 2 * np.pi, num_centers)
fixed_sigma = 0.5

In [4]:
rbf = RBFNetwork(centers, fixed_sigma)

In [9]:
rbf.fit_rbf_units(X=x_train, num_units=7, epochs = 3)

0.0
6.2
Initial centers:
[[2.32214874]
 [5.8944287 ]
 [4.53836244]
 [3.7116826 ]
 [0.96731557]
 [0.96716603]
 [0.3601184 ]]
Epoch 0: Avg win count: 9.0
Epoch 1: Avg win count: 18.0
Epoch 2: Avg win count: 27.0
Final wins per Unit: [14. 10. 11. 11.  7.  3.  7.]
Average Quantization Error (AQE): 2.192084188531515
Average Distance per Unit: [1.67049652 2.78627283 1.91988147 1.62841899 2.26113576 2.30518691
 2.77319683]
Computed widths (sigma): [0.20076935 0.16011961 0.1776175  0.16745823 0.18765604 0.08164966
 0.10265351]
Final centers:
 [[2.33244064]
 [5.85717561]
 [4.5841054 ]
 [3.680386  ]
 [1.03058673]
 [0.95271933]
 [0.34842962]]


(array([[2.33244064],
        [5.85717561],
        [4.5841054 ],
        [3.680386  ],
        [1.03058673],
        [0.95271933],
        [0.34842962]]),
 array([0.20076935, 0.16011961, 0.1776175 , 0.16745823, 0.18765604,
        0.08164966, 0.10265351]))